name: Spoved APP - pipeline
on:
  push:
    branches:
    - development
  pull_request:
    branches:
    - main

jobs:
    provision_infrastructure:
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash 
            working-directory: ./infrastructure/terraform
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
        
        steps:
        # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v3
        
          # Install the preferred version of Terraform CLI 
        - name: HashiCorp - Setup Terraform
          uses: hashicorp/setup-terraform@v3

           # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
        - name: Terraform Init
          id: init
          run: |
            export ARM_CLIENT_ID=$ARM_CLIENT_ID
            export ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET
            export ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID
            export ARM_TENANT_ID=$ARM_TENANT_ID
 
            terraform init
          env:
            ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
            ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}

        # Run a terraform plan for pull requests only
        - name: Terraform Plan
          id: plan
          run: terraform plan -no-color -input=false