name: Spoved APP - pipeline
on:
  push:
    branches:
    - development
  pull_request:
    branches:
    - main

jobs:
    provision_infrastructure:
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash 
            working-directory: ./infrastructure/terraform
        
        steps:
        # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v3
        
          # Install the preferred version of Terraform CLI 
        - name: HashiCorp - Setup Terraform
          uses: hashicorp/setup-terraform@v3

           # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
        - name: Terraform Init
          id: init
          env:
            AZ_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
            AZ_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
            AZ_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            AZ_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
            STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
            CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
          run: terraform init \ 
              -backend-config="subscription_id=$AZ_SUBSCRIPTION_ID" \
              -backend-config="tenant_id=$AZ_TENANT_ID" \
              -backend-config="client_id=$AZ_CLIENT_ID" \ 
              -backend-config="client_secret=$AZ_CLIENT_SECRET" \
              -backend-config="resource_group_name=$RESOURCE_GROUP" \ 
              -backend-config="storage_account_name=$STORAGE_ACCOUNT" \ 
              -backend-config="container_name=$CONTAINER_NAME"

        # Run a terraform plan for pull requests only
        - name: Terraform Plan
          id: plan
          env:
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          run: terraform plan -no-color -input=false